name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Caching objects
      id: cache-objects
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-npm-objects

    - name: npm install
      run: npm install

    - name: pre-commit
      run: |
        pip install pre-commit
        pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit-hooks
        pre-commit run --all-files
